services:
  postgres:
    image: postgis/postgis:${POSTGIS_VERSION}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - elmenus-lite-network

  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres
    restart: unless-stopped
    ports:
      - "9090:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - elmenus-lite-network

  app:
    build: .
    container_name: elmenus-lite
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - elmenus-lite-network


volumes:
  postgres-data:
    driver: local
  pgadmin-data:

networks:
  elmenus-lite-network:
    driver: bridge