version: '3.8'

services:
  postgres:
    image: postgis/postgis:16-3.4-alpine
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: elmenus
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  springboot:
    build: .
    container_name: my_spring_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/elmenus
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password

volumes:
  pgdata: